/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package aplikasietikabisnis;

import javax.swing.JOptionPane;

/**
 *
 * @author USER
 */
public class MainView extends javax.swing.JFrame {

    /**
     * Creates new form MainView
     */
    String namapengirim,alamatpengirim,kodepospengirim,tanggal,namapenerima,alamatpenerima,kodepospenerima,penerima,opening,focus,action,closing,pengirim,jabatan;;
    public MainView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bodyPanel = new javax.swing.JPanel();
        menuPanel = new javax.swing.JPanel();
        btnTips = new javax.swing.JButton();
        btnSurat = new javax.swing.JButton();
        btnKeluar = new javax.swing.JButton();
        btnHome = new javax.swing.JButton();
        btnEtika = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnTentang = new javax.swing.JButton();
        mainPanel = new javax.swing.JPanel();
        homePanel = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jLabel13 = new javax.swing.JLabel();
        etikaPanel = new javax.swing.JPanel();
        btnNext1 = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        tipsPanel = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        btnNext6 = new javax.swing.JButton();
        jScrollPane10 = new javax.swing.JScrollPane();
        jTextArea10 = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextArea4 = new javax.swing.JTextArea();
        suratPanel = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel30 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jLabel36 = new javax.swing.JLabel();
        jTextField8 = new javax.swing.JTextField();
        jLabel37 = new javax.swing.JLabel();
        jTextField9 = new javax.swing.JTextField();
        jLabel38 = new javax.swing.JLabel();
        jTextField10 = new javax.swing.JTextField();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jTextField11 = new javax.swing.JTextField();
        jTextField12 = new javax.swing.JTextField();
        jLabel41 = new javax.swing.JLabel();
        jTextField13 = new javax.swing.JTextField();
        jLabel42 = new javax.swing.JLabel();
        jTextField14 = new javax.swing.JTextField();
        etikanext1Panel = new javax.swing.JPanel();
        btnNext2 = new javax.swing.JButton();
        btnPrev1 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea3 = new javax.swing.JTextArea();
        jLabel47 = new javax.swing.JLabel();
        jScrollPane11 = new javax.swing.JScrollPane();
        jTextArea11 = new javax.swing.JTextArea();
        jScrollPane12 = new javax.swing.JScrollPane();
        jTextArea12 = new javax.swing.JTextArea();
        jLabel48 = new javax.swing.JLabel();
        etikanext2Panel = new javax.swing.JPanel();
        btnNext3 = new javax.swing.JButton();
        btnPrev2 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTextArea5 = new javax.swing.JTextArea();
        jScrollPane14 = new javax.swing.JScrollPane();
        jTextArea14 = new javax.swing.JTextArea();
        jLabel43 = new javax.swing.JLabel();
        etikanext3Panel = new javax.swing.JPanel();
        btnPrev3 = new javax.swing.JButton();
        tipsnext1Panel = new javax.swing.JPanel();
        btnNext4 = new javax.swing.JButton();
        btnPrev6 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        tipsnext2Panel = new javax.swing.JPanel();
        btnNext5 = new javax.swing.JButton();
        btnPrev5 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        tipsnext3Panel = new javax.swing.JPanel();
        btnPrev4 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Aplikasi Etika Bisnis Panel");

        bodyPanel.setBackground(new java.awt.Color(255, 204, 51));

        menuPanel.setBackground(new java.awt.Color(255, 204, 51));
        menuPanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(255, 255, 255), new java.awt.Color(255, 255, 255), new java.awt.Color(255, 255, 255), new java.awt.Color(255, 255, 255)));

        btnTips.setText("ETIKA SURAT BISNIS");
        btnTips.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTipsActionPerformed(evt);
            }
        });

        btnSurat.setText("BUAT SURAT BISNIS");
        btnSurat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuratActionPerformed(evt);
            }
        });

        btnKeluar.setText("KELUAR");
        btnKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKeluarActionPerformed(evt);
            }
        });

        btnHome.setText("PENGERTIAN");
        btnHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHomeActionPerformed(evt);
            }
        });

        btnEtika.setText("ETIKA BISNIS");
        btnEtika.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEtikaActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\USER\\Pictures\\Sponsor Logo Wallpaper Clipart\\etika2.png")); // NOI18N

        btnTentang.setText("TENTANG");
        btnTentang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTentangActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout menuPanelLayout = new javax.swing.GroupLayout(menuPanel);
        menuPanel.setLayout(menuPanelLayout);
        menuPanelLayout.setHorizontalGroup(
            menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, menuPanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnTips, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnSurat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnKeluar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnHome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnEtika, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnTentang, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE))
                .addContainerGap())
        );
        menuPanelLayout.setVerticalGroup(
            menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, menuPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnHome, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEtika, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnTips, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSurat, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnTentang, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnKeluar, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46))
        );

        mainPanel.setBackground(new java.awt.Color(255, 204, 51));
        mainPanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(255, 255, 255), new java.awt.Color(255, 255, 255), new java.awt.Color(255, 255, 255), new java.awt.Color(255, 255, 255)));
        mainPanel.setLayout(new java.awt.CardLayout());

        homePanel.setBackground(new java.awt.Color(153, 255, 51));

        jLabel12.setFont(new java.awt.Font("Bookman Old Style", 1, 16)); // NOI18N
        jLabel12.setText("Pengertian Etika Bisnis");

        jTextArea1.setBackground(new java.awt.Color(153, 255, 51));
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        jTextArea1.setRows(5);
        jTextArea1.setText("Etika bisnis dapat diartikan sebagai peraturan tidak tertulis sebagai landasan norma dan perilaku yang \nharus dipatuhi oleh seluruh lapisan dalam perusahaan. Dengan menjalankan etika bisnis yang baik, \nsebuah perusahaan bisa mendapat nilai dan kepercayaan lebih dari masyarakat, negara, dan bahkan \nkompetitornya. ");
        jScrollPane1.setViewportView(jTextArea1);

        jTextArea2.setBackground(new java.awt.Color(153, 255, 51));
        jTextArea2.setColumns(20);
        jTextArea2.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        jTextArea2.setRows(5);
        jTextArea2.setText("Tujuan berbisnis salah satunya memberikan kesadaran akan perilaku dan moral kepada pemilik bisnis \nagar menjalankan bisnisnya dengan baik. Manfaat Etika Bisnis adalah Kredibilitas perusahaan meningkat, \nBisnis memiliki citra yang baik bagi konsumen, Bisnis akan berjalan secara aman dan nyaman, \nMenciptakan hubungan baik antara konsumen dan pebisnis");
        jScrollPane2.setViewportView(jTextArea2);

        jLabel13.setFont(new java.awt.Font("Bookman Old Style", 1, 16)); // NOI18N
        jLabel13.setText("Tujuan dan Manfaat Etika Bisnis");

        javax.swing.GroupLayout homePanelLayout = new javax.swing.GroupLayout(homePanel);
        homePanel.setLayout(homePanelLayout);
        homePanelLayout.setHorizontalGroup(
            homePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addComponent(jScrollPane2)
            .addGroup(homePanelLayout.createSequentialGroup()
                .addGroup(homePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(homePanelLayout.createSequentialGroup()
                        .addGap(256, 256, 256)
                        .addComponent(jLabel12))
                    .addGroup(homePanelLayout.createSequentialGroup()
                        .addGap(208, 208, 208)
                        .addComponent(jLabel13)))
                .addContainerGap(232, Short.MAX_VALUE))
        );
        homePanelLayout.setVerticalGroup(
            homePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(homePanelLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(216, Short.MAX_VALUE))
        );

        mainPanel.add(homePanel, "card2");

        etikaPanel.setBackground(new java.awt.Color(102, 255, 204));

        btnNext1.setText(">");
        btnNext1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNext1ActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Bookman Old Style", 1, 16)); // NOI18N
        jLabel14.setText("Prinsip Etika Dalam Bisnis");

        jLabel15.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel15.setText("Jujur adalah salah satu nilai paling dasar yang harus dimiliki dalam berbisnis");

        jLabel3.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jLabel3.setText("1. Jujur");

        jLabel4.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jLabel4.setText("2. Bertingkah laku baik");

        jLabel16.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel16.setText("Bertingkah laku menjadi salah satu etika yang paling diperhatikan, saat berinteraksi dengan berbisnis");

        jLabel17.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jLabel17.setText("3. Menyebutkan nama");

        jLabel18.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel18.setText("Menyebutkan nama atau memberikan kartu nama sudah menjadi etika umum ketika bertemu relasi bisnis");

        jLabel19.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jLabel19.setText("4. Berpakaian rapih");

        jLabel20.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel20.setText("Berpakaian rapi juga berarti Anda menghormati relasi bisnis, pimpinan, atau perusahaan");

        jLabel21.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jLabel21.setText("5. Menggunakan bahasa yang baik");

        jLabel22.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel22.setText("Bahasa apa pun yang digunakan dalam berkomunikasi, sebaiknya gunakan bahasa yang positif");

        jLabel23.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jLabel23.setText("6. Bersikap sopan");

        jLabel24.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel24.setText("Agar mendapatkan kesan yang baik kepada rekan bisnis Anda, usahakan bersikap sopan dan santun.");

        jLabel25.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jLabel25.setText("7. Berdiri dan Berjabat tangan");

        jLabel26.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel26.setText("Selalu berdiri saat berkenalan dan menjabat tangan mereka. Menunjukkan sikap hormat & menghargai.");

        jLabel27.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jLabel27.setText("8. Mengucapkan terima kasih");

        jLabel28.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel28.setText("Mengucapkan terima kasih secukupnya dan secara formal akan memberikan kesan profesional. ");

        javax.swing.GroupLayout etikaPanelLayout = new javax.swing.GroupLayout(etikaPanel);
        etikaPanel.setLayout(etikaPanelLayout);
        etikaPanelLayout.setHorizontalGroup(
            etikaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(etikaPanelLayout.createSequentialGroup()
                .addGroup(etikaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(etikaPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(etikaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, etikaPanelLayout.createSequentialGroup()
                                .addComponent(jLabel28)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnNext1))
                            .addGroup(etikaPanelLayout.createSequentialGroup()
                                .addGroup(etikaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel15)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel16)
                                    .addComponent(jLabel17)
                                    .addComponent(jLabel18)
                                    .addComponent(jLabel19)
                                    .addComponent(jLabel20)
                                    .addComponent(jLabel21)
                                    .addComponent(jLabel22)
                                    .addComponent(jLabel23)
                                    .addComponent(jLabel24)
                                    .addComponent(jLabel25)
                                    .addComponent(jLabel27))
                                .addGap(0, 33, Short.MAX_VALUE))))
                    .addGroup(etikaPanelLayout.createSequentialGroup()
                        .addGroup(etikaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(etikaPanelLayout.createSequentialGroup()
                                .addGap(244, 244, 244)
                                .addComponent(jLabel14))
                            .addGroup(etikaPanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel26)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        etikaPanelLayout.setVerticalGroup(
            etikaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(etikaPanelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel18)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel19)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel20)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel21)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel22)
                .addGap(11, 11, 11)
                .addComponent(jLabel23)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel24)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel25)
                .addGroup(etikaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(etikaPanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnNext1)
                        .addContainerGap())
                    .addGroup(etikaPanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel26)
                        .addGap(3, 3, 3)
                        .addComponent(jLabel27)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel28)
                        .addContainerGap(87, Short.MAX_VALUE))))
        );

        mainPanel.add(etikaPanel, "card3");

        tipsPanel.setBackground(new java.awt.Color(255, 255, 153));

        jLabel5.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jLabel5.setText("ETIKA PENULISAN SURAT BISNIS ");

        btnNext6.setText(">");
        btnNext6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNext6ActionPerformed(evt);
            }
        });

        jTextArea10.setBackground(new java.awt.Color(255, 255, 153));
        jTextArea10.setColumns(20);
        jTextArea10.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jTextArea10.setRows(5);
        jTextArea10.setText("Adapun etika dan teknik menulis surat bisnis adalah sebagai berikut :\n\n1. Tulislah rujukan surat diawal atau pembukaan surat agar penerima memahami alur dari surat.\n2. Buatlah isi surat dengan simple, ringkas, jelas, mudah dipahami apa maksud dan tujuan \n    surat serta tidak bertele-tele.\n3. Gunakan tanda baca secara tepat, benar dengan ejaan yang jelas dan tata bahasa yang benar.\n4. Gunakan bahasa Indonesia yang benar. Hindari kalimat perintah/kalimat yang memojokkan, \n     berdebat, sekalipun surat tersebut berisi komplain terhadap pelanggan kita, namun perlu \n     disampaikan dengan santun serta kemungkinan solusi dari permasalahan.\n5. Gunakan kalimat/kata yang sistematis, jangan menggunakan kata-kata yang mempunyai arti \n     ganda yang menimbulkan kerancuan.\n6. Jika menyampaikan data atau informasi harus tepat dan benar apalagi yang menyangkut angka.\n7. Bacalah dan lakukan koreksi berulang jika dibutuhkan agar mendapatkan surat bisnis yang \n    terbaik, bagaimanapun juga cara menulis surat mencerminkan kapasitas penulis.");
        jScrollPane10.setViewportView(jTextArea10);

        jTextArea4.setBackground(new java.awt.Color(255, 255, 153));
        jTextArea4.setColumns(20);
        jTextArea4.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        jTextArea4.setRows(5);
        jTextArea4.setText("Setelah memahami etika menulis surat bisni terdapat hal bagian-bagian isi surat bisnis yaitu:\n\n1. Kop surat berisi nama perusahaan pengirim, alamat, nomor, dan kode pos\n2. Tanggal pada saat surat\n3. Alamat penerima surat bisnis tersebut berisi nama perusahaan, alamat, nomor, dan kode pos\n4. Tulis salam pembuka, seperti Kepada Yth,\n5. Isi surat terdiri dari 4 bagian yaitu pembukaan, fokus, aksi, penutup\n6. Tulis salam penutup, seperti Dengan hormat,\n7. Cantumkan nama pengirim surat, tanda tangan, dan jabatan ");
        jScrollPane4.setViewportView(jTextArea4);

        javax.swing.GroupLayout tipsPanelLayout = new javax.swing.GroupLayout(tipsPanel);
        tipsPanel.setLayout(tipsPanelLayout);
        tipsPanelLayout.setHorizontalGroup(
            tipsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tipsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(tipsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane4)
                    .addComponent(jScrollPane10, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tipsPanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnNext6))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, tipsPanelLayout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(0, 424, Short.MAX_VALUE)))
                .addContainerGap())
        );
        tipsPanelLayout.setVerticalGroup(
            tipsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tipsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addComponent(btnNext6)
                .addContainerGap())
        );

        mainPanel.add(tipsPanel, "card4");

        suratPanel.setBackground(new java.awt.Color(153, 153, 255));

        jLabel6.setText("BUAT SURAT BISNIS: SURAT PERMINTAAN (INQUIRY LETTER)");

        jLabel29.setText("Nama Perusahaan Pengirim:");

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jButton1.setText("Buat Surat");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel30.setText("Alamat Perusahaan Pengirim:");

        jLabel31.setText("Nomor Kode Pos Daerah Perusahaan Pengirim:");

        jLabel32.setText("Tanggal Surat:");

        jLabel33.setText("Nama Perusahaan Penerima:");

        jLabel34.setText("Alamat Perusahaan Penerima:");

        jLabel35.setText("Nomor Kode Pos Daerah Perusahaan Penerima:");

        jLabel36.setText("Nama Penerima Surat:");

        jLabel37.setText("Masukan Isi Pembuka (Jelaskan alasan anda menulis surat):");

        jLabel38.setText("Masukan Fokus (Perkenalkan diri dan perusahaan bisnis anda):");

        jLabel39.setText("Masukan Aksi (Uraikan informasi tentang bisnis jasa/barang yang anda ingin ketahui):");

        jLabel40.setText("Masukan Isi Penutup (Ucapan penutup dan terimakasih):");

        jLabel41.setText("Nama Pengirim Surat:");

        jLabel42.setText("Jabatan Pengirim Surat pada perusahaan:");

        javax.swing.GroupLayout suratPanelLayout = new javax.swing.GroupLayout(suratPanel);
        suratPanel.setLayout(suratPanelLayout);
        suratPanelLayout.setHorizontalGroup(
            suratPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(suratPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(suratPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton1)
                    .addGroup(suratPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel6)
                        .addGroup(suratPanelLayout.createSequentialGroup()
                            .addComponent(jLabel29)
                            .addGap(18, 18, 18)
                            .addComponent(jTextField1))
                        .addGroup(suratPanelLayout.createSequentialGroup()
                            .addComponent(jLabel30)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jTextField2))
                        .addGroup(suratPanelLayout.createSequentialGroup()
                            .addComponent(jLabel35)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jTextField7))
                        .addGroup(suratPanelLayout.createSequentialGroup()
                            .addComponent(jLabel34)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jTextField6))
                        .addGroup(suratPanelLayout.createSequentialGroup()
                            .addComponent(jLabel33)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jTextField5))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, suratPanelLayout.createSequentialGroup()
                            .addComponent(jLabel32)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jTextField4))
                        .addGroup(suratPanelLayout.createSequentialGroup()
                            .addComponent(jLabel31)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jTextField3))
                        .addGroup(suratPanelLayout.createSequentialGroup()
                            .addComponent(jLabel36)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jTextField8))
                        .addGroup(suratPanelLayout.createSequentialGroup()
                            .addComponent(jLabel37)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(suratPanelLayout.createSequentialGroup()
                            .addComponent(jLabel38)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jTextField10))
                        .addGroup(suratPanelLayout.createSequentialGroup()
                            .addComponent(jLabel39)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jTextField11))
                        .addGroup(suratPanelLayout.createSequentialGroup()
                            .addComponent(jLabel40)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jTextField12))
                        .addGroup(suratPanelLayout.createSequentialGroup()
                            .addComponent(jLabel42)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jTextField14))
                        .addGroup(suratPanelLayout.createSequentialGroup()
                            .addComponent(jLabel41)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jTextField13))))
                .addContainerGap(122, Short.MAX_VALUE))
        );
        suratPanelLayout.setVerticalGroup(
            suratPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(suratPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addGroup(suratPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel29)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(suratPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel30)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(suratPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel31)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(suratPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel32)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(suratPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel33)
                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(suratPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel34)
                    .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(suratPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel35)
                    .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(suratPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel36)
                    .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(suratPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel37)
                    .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(suratPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(suratPanelLayout.createSequentialGroup()
                        .addComponent(jLabel38)
                        .addGap(18, 18, 18)
                        .addGroup(suratPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel39)
                            .addComponent(jTextField11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(suratPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel40)
                            .addComponent(jTextField12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(suratPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel41)
                            .addComponent(jTextField13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(suratPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel42)
                            .addComponent(jTextField14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addContainerGap(80, Short.MAX_VALUE))
        );

        mainPanel.add(suratPanel, "card5");

        etikanext1Panel.setBackground(new java.awt.Color(153, 255, 255));

        btnNext2.setText(">");
        btnNext2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNext2ActionPerformed(evt);
            }
        });

        btnPrev1.setText("<");
        btnPrev1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrev1ActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel9.setText("ETIKA BISNIS MENCAKUP");

        jTextArea3.setBackground(new java.awt.Color(153, 255, 255));
        jTextArea3.setColumns(20);
        jTextArea3.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jTextArea3.setRows(5);
        jTextArea3.setText("- Etika bisnis mencakup hubungan antara perusahaan dengan perusahaan, investor,\n  konsumen, pegawai, kreditur dan pesaing\n- Produsen menghasilkan produk untuk memenuhi kebutuhan para konsumen\n- Konsumen menginginkan agar perusahaan menghasilkan produk bermutu yang dapat \n  dipercaya dan dengan harga yang layak");
        jScrollPane3.setViewportView(jTextArea3);

        jLabel47.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jLabel47.setText("HAK PRODUSEN");

        jTextArea11.setBackground(new java.awt.Color(153, 255, 255));
        jTextArea11.setColumns(20);
        jTextArea11.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jTextArea11.setRows(5);
        jTextArea11.setText("1. Hak menerima pembayaran yang sesuai dengan kesepakatan barang/jasa yang diperdagang\n    kan\n2. Hak untuk mendapat perlindungan hukum dari tindakan konsumen yang beritikad tidak baik\n3. Hak untuk melakukan pembelaan diri sepatutnya di dalam penyelesaian hukum sengketa \n    konsumen");
        jScrollPane11.setViewportView(jTextArea11);

        jTextArea12.setBackground(new java.awt.Color(153, 255, 255));
        jTextArea12.setColumns(20);
        jTextArea12.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jTextArea12.setRows(5);
        jTextArea12.setText("1. Hak atas kenyamanan, keamanan, dan keselamatan dalam mengkonsumsi barang \n    dan jasa\n2. Hak untuk memilih barang dan jasa serta mendapatkan barang\n3. Hak atas informasi yang benar, jelas, dan jujur mengenai kondisi dan jaminan\n    barang dan jasa\n4. Hak untuk di dengar pendapat dan keluhannya atas barang dan jasa\n5. Hak untuk dilayani atau diperlakukan secara benar dan jujur tidak diskriminatif");
        jScrollPane12.setViewportView(jTextArea12);

        jLabel48.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jLabel48.setText("HAK KONSUMEN");

        javax.swing.GroupLayout etikanext1PanelLayout = new javax.swing.GroupLayout(etikanext1Panel);
        etikanext1Panel.setLayout(etikanext1PanelLayout);
        etikanext1PanelLayout.setHorizontalGroup(
            etikanext1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(etikanext1PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(etikanext1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, etikanext1PanelLayout.createSequentialGroup()
                        .addComponent(btnPrev1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 610, Short.MAX_VALUE)
                        .addComponent(btnNext2))
                    .addComponent(jScrollPane3)
                    .addComponent(jScrollPane11)
                    .addComponent(jScrollPane12)
                    .addGroup(etikanext1PanelLayout.createSequentialGroup()
                        .addGroup(etikanext1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel47)
                            .addComponent(jLabel48))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        etikanext1PanelLayout.setVerticalGroup(
            etikanext1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, etikanext1PanelLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addComponent(jLabel47)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel48)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane12, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addGroup(etikanext1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNext2)
                    .addComponent(btnPrev1))
                .addContainerGap())
        );

        mainPanel.add(etikanext1Panel, "card6");

        etikanext2Panel.setBackground(new java.awt.Color(153, 255, 255));

        btnNext3.setText(">");
        btnNext3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNext3ActionPerformed(evt);
            }
        });

        btnPrev2.setText("<");
        btnPrev2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrev2ActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jLabel10.setText("ETIKA KONSUMEN");

        jTextArea5.setBackground(new java.awt.Color(153, 255, 255));
        jTextArea5.setColumns(20);
        jTextArea5.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jTextArea5.setRows(5);
        jTextArea5.setText("1. Membaca dan mengikuti petunjuk informasi dan prosedur pemakaian atau pemanfaatan barang\n    atau jasa demi keselamatan dan keamanan\n2. Beritikad baik dalam melakukan transaksi pembelian barang atau jasa\n3. Membayar sesuai dengan nilai tukar atau harga yang disepakati");
        jScrollPane5.setViewportView(jTextArea5);

        jTextArea14.setBackground(new java.awt.Color(153, 255, 255));
        jTextArea14.setColumns(20);
        jTextArea14.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jTextArea14.setRows(5);
        jTextArea14.setText("1. Beritikad baik dalam kegiatan usahanya\n2. Memberikan informasi yang benar, jelas dan jujur mengenai kondisi barang/jasa\n3. Melayani konsumen secara benar dan jujur serta tidak diskriminatif\n4. Menjamin mutu barang/jasa yang diproduksi/diperdagangkan berdasarkan ketentuan standar\n5. Memberi kompensasi ganti rugi, penggantian kerugian akibat penggunaan/pemakaian barang\n    /jasa yang diperdagangkan\n6. Memberi kompensasi ganti rugi, penggantian kerugian akibat barang yang diterima tidak sesuai");
        jScrollPane14.setViewportView(jTextArea14);

        jLabel43.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jLabel43.setText("ETIKA PRODUSEN");

        javax.swing.GroupLayout etikanext2PanelLayout = new javax.swing.GroupLayout(etikanext2Panel);
        etikanext2Panel.setLayout(etikanext2PanelLayout);
        etikanext2PanelLayout.setHorizontalGroup(
            etikanext2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(etikanext2PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(etikanext2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane5)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, etikanext2PanelLayout.createSequentialGroup()
                        .addComponent(btnPrev2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 610, Short.MAX_VALUE)
                        .addComponent(btnNext3))
                    .addComponent(jScrollPane14)
                    .addGroup(etikanext2PanelLayout.createSequentialGroup()
                        .addGroup(etikanext2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(jLabel43))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        etikanext2PanelLayout.setVerticalGroup(
            etikanext2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, etikanext2PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel43)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane14, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 207, Short.MAX_VALUE)
                .addGroup(etikanext2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNext3)
                    .addComponent(btnPrev2))
                .addContainerGap())
        );

        mainPanel.add(etikanext2Panel, "card7");

        etikanext3Panel.setBackground(new java.awt.Color(153, 255, 255));

        btnPrev3.setText("<");
        btnPrev3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrev3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout etikanext3PanelLayout = new javax.swing.GroupLayout(etikanext3Panel);
        etikanext3Panel.setLayout(etikanext3PanelLayout);
        etikanext3PanelLayout.setHorizontalGroup(
            etikanext3PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, etikanext3PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnPrev3)
                .addContainerGap(661, Short.MAX_VALUE))
        );
        etikanext3PanelLayout.setVerticalGroup(
            etikanext3PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, etikanext3PanelLayout.createSequentialGroup()
                .addContainerGap(538, Short.MAX_VALUE)
                .addComponent(btnPrev3)
                .addContainerGap())
        );

        mainPanel.add(etikanext3Panel, "card8");

        tipsnext1Panel.setBackground(new java.awt.Color(255, 153, 153));

        btnNext4.setText(">");
        btnNext4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNext4ActionPerformed(evt);
            }
        });

        btnPrev6.setText("<");
        btnPrev6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrev6ActionPerformed(evt);
            }
        });

        jLabel8.setText("MENU TIPS 1");

        javax.swing.GroupLayout tipsnext1PanelLayout = new javax.swing.GroupLayout(tipsnext1Panel);
        tipsnext1Panel.setLayout(tipsnext1PanelLayout);
        tipsnext1PanelLayout.setHorizontalGroup(
            tipsnext1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tipsnext1PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(tipsnext1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tipsnext1PanelLayout.createSequentialGroup()
                        .addComponent(btnPrev6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 610, Short.MAX_VALUE)
                        .addComponent(btnNext4))
                    .addGroup(tipsnext1PanelLayout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        tipsnext1PanelLayout.setVerticalGroup(
            tipsnext1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tipsnext1PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 513, Short.MAX_VALUE)
                .addGroup(tipsnext1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNext4)
                    .addComponent(btnPrev6))
                .addContainerGap())
        );

        mainPanel.add(tipsnext1Panel, "card9");

        tipsnext2Panel.setBackground(new java.awt.Color(255, 153, 153));

        btnNext5.setText(">");
        btnNext5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNext5ActionPerformed(evt);
            }
        });

        btnPrev5.setText("<");
        btnPrev5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrev5ActionPerformed(evt);
            }
        });

        jLabel7.setText("MENU TIPS 2");

        javax.swing.GroupLayout tipsnext2PanelLayout = new javax.swing.GroupLayout(tipsnext2Panel);
        tipsnext2Panel.setLayout(tipsnext2PanelLayout);
        tipsnext2PanelLayout.setHorizontalGroup(
            tipsnext2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tipsnext2PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(tipsnext2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tipsnext2PanelLayout.createSequentialGroup()
                        .addComponent(btnPrev5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 610, Short.MAX_VALUE)
                        .addComponent(btnNext5))
                    .addGroup(tipsnext2PanelLayout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        tipsnext2PanelLayout.setVerticalGroup(
            tipsnext2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tipsnext2PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 513, Short.MAX_VALUE)
                .addGroup(tipsnext2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNext5)
                    .addComponent(btnPrev5))
                .addContainerGap())
        );

        mainPanel.add(tipsnext2Panel, "card10");

        tipsnext3Panel.setBackground(new java.awt.Color(255, 153, 153));

        btnPrev4.setText("<");
        btnPrev4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrev4ActionPerformed(evt);
            }
        });

        jLabel2.setText("MENU TIPS 3");

        javax.swing.GroupLayout tipsnext3PanelLayout = new javax.swing.GroupLayout(tipsnext3Panel);
        tipsnext3Panel.setLayout(tipsnext3PanelLayout);
        tipsnext3PanelLayout.setHorizontalGroup(
            tipsnext3PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tipsnext3PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(tipsnext3PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnPrev4)
                    .addComponent(jLabel2))
                .addContainerGap(640, Short.MAX_VALUE))
        );
        tipsnext3PanelLayout.setVerticalGroup(
            tipsnext3PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tipsnext3PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 513, Short.MAX_VALUE)
                .addComponent(btnPrev4)
                .addContainerGap())
        );

        mainPanel.add(tipsnext3Panel, "card11");

        javax.swing.GroupLayout bodyPanelLayout = new javax.swing.GroupLayout(bodyPanel);
        bodyPanel.setLayout(bodyPanelLayout);
        bodyPanelLayout.setHorizontalGroup(
            bodyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bodyPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(menuPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        bodyPanelLayout.setVerticalGroup(
            bodyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bodyPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(bodyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(menuPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bodyPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bodyPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHomeActionPerformed
        // TODO add your handling code here:
        
        // REMOVE PANEL
        mainPanel.removeAll();
        mainPanel.repaint();
        mainPanel.revalidate();
        
        // ADD PANEL SELANJUTNYA
        mainPanel.add(homePanel);
        mainPanel.repaint();
        mainPanel.revalidate();
    }//GEN-LAST:event_btnHomeActionPerformed

    private void btnEtikaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEtikaActionPerformed
        // TODO add your handling code here:
        // REMOVE PANEL
        mainPanel.removeAll();
        mainPanel.repaint();
        mainPanel.revalidate();
        
        // ADD PANEL SELANJUTNYA
        mainPanel.add(etikaPanel);
        mainPanel.repaint();
        mainPanel.revalidate();
    }//GEN-LAST:event_btnEtikaActionPerformed

    private void btnTipsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTipsActionPerformed
        // TODO add your handling code here:
        // REMOVE PANEL
        mainPanel.removeAll();
        mainPanel.repaint();
        mainPanel.revalidate();
        
        // ADD PANEL SELANJUTNYA
        mainPanel.add(tipsPanel);
        mainPanel.repaint();
        mainPanel.revalidate();
    }//GEN-LAST:event_btnTipsActionPerformed

    private void btnSuratActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuratActionPerformed
        // TODO add your handling code here:
        // REMOVE PANEL
        mainPanel.removeAll();
        mainPanel.repaint();
        mainPanel.revalidate();
        
        // ADD PANEL SELANJUTNYA
        mainPanel.add(suratPanel);
        mainPanel.repaint();
        mainPanel.revalidate();
    }//GEN-LAST:event_btnSuratActionPerformed

    private void btnKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKeluarActionPerformed
        // TODO add your handling code here:
        int dialogBtn = JOptionPane.YES_NO_OPTION;
        int dialogResult = JOptionPane.showConfirmDialog(this, "Anda Yakin akan keluar?", "Peringatan", dialogBtn);
        
        if(dialogResult==0){
        //true kondisi
        System.exit(0);
        } else {
            //kondisi salah
        }
    }//GEN-LAST:event_btnKeluarActionPerformed

    private void btnTentangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTentangActionPerformed
        // TODO add your handling code here:
        AboutView n = new AboutView();
        n.setVisible(true);
    }//GEN-LAST:event_btnTentangActionPerformed

    private void btnNext1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNext1ActionPerformed
        // TODO add your handling code here:
        // REMOVE PANEL
        mainPanel.removeAll();
        mainPanel.repaint();
        mainPanel.revalidate();
        
        // ADD PANEL SELANJUTNYA
        mainPanel.add(etikanext1Panel);
        mainPanel.repaint();
        mainPanel.revalidate();
    }//GEN-LAST:event_btnNext1ActionPerformed

    private void btnNext2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNext2ActionPerformed
        // TODO add your handling code here:
                // REMOVE PANEL
        mainPanel.removeAll();
        mainPanel.repaint();
        mainPanel.revalidate();
        
        // ADD PANEL SELANJUTNYA
        mainPanel.add(etikanext2Panel);
        mainPanel.repaint();
        mainPanel.revalidate();
    }//GEN-LAST:event_btnNext2ActionPerformed

    private void btnPrev3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrev3ActionPerformed
        // TODO add your handling code here:
        // REMOVE PANEL
        mainPanel.removeAll();
        mainPanel.repaint();
        mainPanel.revalidate();
        
        // ADD PANEL SELANJUTNYA
        mainPanel.add(etikanext2Panel);
        mainPanel.repaint();
        mainPanel.revalidate();
    }//GEN-LAST:event_btnPrev3ActionPerformed

    private void btnPrev1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrev1ActionPerformed
        // TODO add your handling code here:
        // REMOVE PANEL
        mainPanel.removeAll();
        mainPanel.repaint();
        mainPanel.revalidate();
        
        // ADD PANEL SELANJUTNYA
        mainPanel.add(etikaPanel);
        mainPanel.repaint();
        mainPanel.revalidate();
    }//GEN-LAST:event_btnPrev1ActionPerformed

    private void btnNext6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNext6ActionPerformed
        // TODO add your handling code here:
        // REMOVE PANEL
        mainPanel.removeAll();
        mainPanel.repaint();
        mainPanel.revalidate();
        
        // ADD PANEL SELANJUTNYA
        mainPanel.add(tipsnext1Panel);
        mainPanel.repaint();
        mainPanel.revalidate();
    }//GEN-LAST:event_btnNext6ActionPerformed

    private void btnPrev6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrev6ActionPerformed
        // TODO add your handling code here:
        // REMOVE PANEL
        mainPanel.removeAll();
        mainPanel.repaint();
        mainPanel.revalidate();
        
        // ADD PANEL SELANJUTNYA
        mainPanel.add(tipsPanel);
        mainPanel.repaint();
        mainPanel.revalidate();
    }//GEN-LAST:event_btnPrev6ActionPerformed

    private void btnNext4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNext4ActionPerformed
        // TODO add your handling code here:
        // REMOVE PANEL
        mainPanel.removeAll();
        mainPanel.repaint();
        mainPanel.revalidate();
        
        // ADD PANEL SELANJUTNYA
        mainPanel.add(tipsnext2Panel);
        mainPanel.repaint();
        mainPanel.revalidate();
    }//GEN-LAST:event_btnNext4ActionPerformed

    private void btnPrev5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrev5ActionPerformed
        // TODO add your handling code here:
        // REMOVE PANEL
        mainPanel.removeAll();
        mainPanel.repaint();
        mainPanel.revalidate();
        
        // ADD PANEL SELANJUTNYA
        mainPanel.add(tipsnext1Panel);
        mainPanel.repaint();
        mainPanel.revalidate();
    }//GEN-LAST:event_btnPrev5ActionPerformed

    private void btnNext5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNext5ActionPerformed
        // TODO add your handling code here:
        // REMOVE PANEL
        mainPanel.removeAll();
        mainPanel.repaint();
        mainPanel.revalidate();
        
        // ADD PANEL SELANJUTNYA
        mainPanel.add(tipsnext3Panel);
        mainPanel.repaint();
        mainPanel.revalidate();
    }//GEN-LAST:event_btnNext5ActionPerformed

    private void btnPrev4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrev4ActionPerformed
        // TODO add your handling code here:
        // REMOVE PANEL
        mainPanel.removeAll();
        mainPanel.repaint();
        mainPanel.revalidate();
        
        // ADD PANEL SELANJUTNYA
        mainPanel.add(tipsnext2Panel);
        mainPanel.repaint();
        mainPanel.revalidate();
    }//GEN-LAST:event_btnPrev4ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        namapengirim = jTextField1.getText();
        alamatpengirim = jTextField2.getText();
        kodepospengirim = jTextField3.getText();
        tanggal = jTextField4.getText();
        namapenerima = jTextField5.getText();
        alamatpenerima = jTextField6.getText();
        kodepospenerima = jTextField7.getText();
        penerima = jTextField8.getText();
        opening = jTextField9.getText();
        focus = jTextField10.getText();
        action = jTextField11.getText();
        closing = jTextField12.getText();
        pengirim = jTextField13.getText();
        jabatan = jTextField14.getText();
        Mail1 m1 = new Mail1(namapengirim, alamatpengirim, kodepospengirim, tanggal, namapenerima, alamatpenerima, kodepospenerima, penerima, opening, focus, action, closing, pengirim, jabatan);
        m1.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnPrev2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrev2ActionPerformed
        // TODO add your handling code here:
        // REMOVE PANEL
        mainPanel.removeAll();
        mainPanel.repaint();
        mainPanel.revalidate();

        // ADD PANEL SELANJUTNYA
        mainPanel.add(etikanext1Panel);
        mainPanel.repaint();
        mainPanel.revalidate();
    }//GEN-LAST:event_btnPrev2ActionPerformed

    private void btnNext3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNext3ActionPerformed
        // TODO add your handling code here:
        // REMOVE PANEL
        mainPanel.removeAll();
        mainPanel.repaint();
        mainPanel.revalidate();

        // ADD PANEL SELANJUTNYA
        mainPanel.add(etikanext3Panel);
        mainPanel.repaint();
        mainPanel.revalidate();
    }//GEN-LAST:event_btnNext3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bodyPanel;
    private javax.swing.JButton btnEtika;
    private javax.swing.JButton btnHome;
    private javax.swing.JButton btnKeluar;
    private javax.swing.JButton btnNext1;
    private javax.swing.JButton btnNext2;
    private javax.swing.JButton btnNext3;
    private javax.swing.JButton btnNext4;
    private javax.swing.JButton btnNext5;
    private javax.swing.JButton btnNext6;
    private javax.swing.JButton btnPrev1;
    private javax.swing.JButton btnPrev2;
    private javax.swing.JButton btnPrev3;
    private javax.swing.JButton btnPrev4;
    private javax.swing.JButton btnPrev5;
    private javax.swing.JButton btnPrev6;
    private javax.swing.JButton btnSurat;
    private javax.swing.JButton btnTentang;
    private javax.swing.JButton btnTips;
    private javax.swing.JPanel etikaPanel;
    private javax.swing.JPanel etikanext1Panel;
    private javax.swing.JPanel etikanext2Panel;
    private javax.swing.JPanel etikanext3Panel;
    private javax.swing.JPanel homePanel;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane11;
    private javax.swing.JScrollPane jScrollPane12;
    private javax.swing.JScrollPane jScrollPane14;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea10;
    private javax.swing.JTextArea jTextArea11;
    private javax.swing.JTextArea jTextArea12;
    private javax.swing.JTextArea jTextArea14;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextArea jTextArea3;
    private javax.swing.JTextArea jTextArea4;
    private javax.swing.JTextArea jTextArea5;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField14;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JPanel menuPanel;
    private javax.swing.JPanel suratPanel;
    private javax.swing.JPanel tipsPanel;
    private javax.swing.JPanel tipsnext1Panel;
    private javax.swing.JPanel tipsnext2Panel;
    private javax.swing.JPanel tipsnext3Panel;
    // End of variables declaration//GEN-END:variables
}
